### ISSUE TITLE
Support for styled components 4

### ISSUE THREAD

**Issue by ulrichb** [dmitrymorozoff/react-spinners-kit#3]
Please add v4 support for styled components.

If it's already supported, please just change the peerDependencies entry to 2.x || 4.x to fix the npm warnings when installing react-spinners-kit. (Note that the current ^2.x does not include v4 in its range.)

**Comment by dmitrymorozoff** [comment]
@ulrichb Soon I will rewrite the library on pure css. This will reduce the size of the final bundle.

**Comment by netvariableteam** [comment]
Error: Can't resolve 'styled-components

**Comment by taraldjoh** [comment]
Any updates here? I'm having serious issues regarding having Styled Components on ^2x instead of v4. It causes instance issues and It's simply not usable without having this fixed.

**Comment by dmitrymorozoff** [comment]
Good.  In the coming days I will try to fix it. Unfortunately now I have a lot of work.  But I will try to do

**Comment by alsmith808** [comment]
Is this library usable, I get the error..

> Module not found: Can't resolve 'styled-components'

**Comment by alsmith808** [comment]
Scratch that, just installed styled components and all good, thanks, nice spinners Dimitri.

**Comment by dmitrymorozoff** [comment]
@ulrichb fixed in 1.9.1

**Comment by ulrichb** [comment]
@dmitrymorozoff: Many thanks!
