### ISSUE TITLE
Some of the props are lowercase

### ISSUE THREAD

**Issue by rohitkrishna094** [dmitrymorozoff/react-spinners-kit#6]
In the readme, the props are capitalized. I think all props are lowercase. Like for example the proptype color is not 'Color' but its 'color'. This confused for about 10 minutes. Would be better if we change the readme to lowercase. I know its obvious that it would be lowercase, but just putting it out here in case anyone might need it.

**Comment by dmitrymorozoff** [comment]
@rohitkrishna094 fixed
